apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: cluster_name
spec:
  project: default
  destination:
    server: https://172.18.255.200:443?agentName=cluster_name # Replace with https://<principal-external-ip:port>?agentName=<managed-cluster-name>
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.9.13
    helm:
      releaseName: external-secrets-operator
      parameters:
        - name: installCRDs
          value: "true"
