---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: open-cluster-management-argocd
spec:
  project: default
  destination:
    name: in-cluster
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.14.5
    helm:
      releaseName: cert-manager
      values: |
        installCRDs: true
        replicaCount: 2
        podDisruptionBudget:
          enabled: true
          minAvailable: 1
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        prometheus:
          enabled: true
          servicemonitor:
            enabled: true
