---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: open-cluster-management-argocd
spec:
  project: default
  destination:
    name: in-cluster
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    chart: cert-manager
    repoURL: quay.io/jetstack/charts
    targetRevision: v1.19.1  # verificar versão mais recente em https://artifacthub.io/packages/helm/cert-manager
    helm:
      releaseName: cert-manager
      values: |-
        installCRDs: true
        prometheus:
          enabled: true
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jsonPointers:
        - /webhooks
