---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: open-cluster-management-argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  destination:
    name: in-cluster
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.19.2
    helm:
      releaseName: cert-manager
      parameters:
        - name: crds.enabled
          value: 'true'
      # values: |
      #   crds:
      #     enabled: true
      #   replicaCount: 2
      #   podDisruptionBudget:
      #     enabled: true
      #     minAvailable: 1
      #   resources:
      #     requests:
      #       cpu: 100m
      #       memory: 128Mi
      #     limits:
      #       cpu: 500m
      #       memory: 512Mi
      #   prometheus:
      #     enabled: true
      #     servicemonitor:
      #       enabled: true
